"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { createClient,Session } from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://vkhpydcyneknrbmjnmeu.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_cGntHCS7OvZATBIS8Azy_A_cfPKHKbM");
type Profile={id:string;email:string;full_name:string;department:string;role:"employee"|"admin"};
type Report={id?:string;user_id?:string;report_date:string;completed_work:string;in_progress_work:string;issues:string;actions_taken:string;tomorrow_plan:string;status:"draft"|"submitted"|"approved"|"revision_requested";manager_feedback?:string;profiles?:{full_name:string;department:string;email:string}};
type Project={id?:string;owner_id?:string;title:string;summary:string;progress:number;status:"planned"|"active"|"blocked"|"completed";current_update:string;next_action:string;risk:string;target_date:string|null};
const freshReport=():Report=>({report_date:new Date().toISOString().slice(0,10),completed_work:"",in_progress_work:"",issues:"",actions_taken:"",tomorrow_plan:"",status:"draft",manager_feedback:""});
const freshProject=():Project=>({title:"",summary:"",progress:0,status:"planned",current_update:"",next_action:"",risk:"",target_date:null});
const labels:Record<string,string>={draft:"임시저장",submitted:"승인 대기",approved:"승인 완료",revision_requested:"보완 요청",planned:"예정",active:"진행 중",blocked:"지연",completed:"완료"};
export default function Home(){
 const[session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const[mode,setMode]=useState<"login"|"signup">("login"),[auth,setAuth]=useState({email:"",password:"",fullName:""}),[tab,setTab]=useState<"home"|"report"|"projects"|"admin">("home");
 const[report,setReport]=useState<Report>(freshReport()),[reports,setReports]=useState<Report[]>([]),[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project>(freshProject()),[files,setFiles]=useState<File[]>([]),[notice,setNotice]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadAll();else setProfile(null)},[session]);
 async function loadAll(){if(!session)return;const[{data:p},{data:r},{data:pr}]=await Promise.all([supabase.from("profiles").select("*").eq("id",session.user.id).single(),supabase.from("daily_reports").select("*, profiles(full_name,department,email)").order("report_date",{ascending:false}),supabase.from("projects").select("*").order("updated_at",{ascending:false})]);setProfile(p as Profile);setReports((r||[])as Report[]);setProjects((pr||[])as Project[])}
 async function handleAuth(e:FormEvent){e.preventDefault();setBusy(true);setNotice("");const x=mode==="login"?await supabase.auth.signInWithPassword({email:auth.email,password:auth.password}):await supabase.auth.signUp({email:auth.email,password:auth.password,options:{data:{full_name:auth.fullName}}});setBusy(false);if(x.error)setNotice(x.error.message);else if(mode==="signup"&&!x.data.session)setNotice("가입 확인 메일을 확인해 주세요.")}
 function openReport(date:string){const x=reports.find(r=>r.report_date===date);setReport(x?{...x}:{...freshReport(),report_date:date});setFiles([]);setTab("report")}
 async function saveReport(submit=false){if(!session)return;setBusy(true);setNotice("");const payload:any={...report,user_id:session.user.id,status:submit?"submitted":"draft",submitted_at:submit?new Date().toISOString():null,updated_at:new Date().toISOString()};delete payload.profiles;const{data,error}=await supabase.from("daily_reports").upsert(payload,{onConflict:"user_id,report_date"}).select().single();if(!error&&files.length)for(const file of files){const path=`${session.user.id}/${data.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabase.storage.from("report-files").upload(path,file);if(!up.error)await supabase.from("attachments").insert({user_id:session.user.id,report_id:data.id,file_name:file.name,file_path:path,file_type:file.type,file_size:file.size})}setBusy(false);setNotice(error?error.message:submit?"보고서를 제출했습니다.":"임시저장했습니다.");if(!error){setReport(data as Report);setFiles([]);await loadAll()}}
 async function saveProject(e:FormEvent){e.preventDefault();if(!session)return;setBusy(true);const{error}=await supabase.from("projects").upsert({...project,owner_id:session.user.id,updated_at:new Date().toISOString()});setBusy(false);setNotice(error?error.message:"프로젝트를 저장했습니다.");if(!error){setProject(freshProject());await loadAll()}}
 async function review(id:string,status:"approved"|"revision_requested"){const feedback=status==="revision_requested"?prompt("보완 요청 내용을 입력해 주세요."):"확인했습니다.";if(feedback===null)return;const{error}=await supabase.from("daily_reports").update({status,manager_feedback:feedback,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);setNotice(error?error.message:status==="approved"?"승인했습니다.":"보완을 요청했습니다.");await loadAll()}
 const today=useMemo(()=>reports.find(r=>r.report_date===new Date().toISOString().slice(0,10)),[reports]),waiting=reports.filter(r=>r.status==="submitted");
 if(loading)return <main className="center"><div className="spinner"/></main>;
 if(!session)return <main className="auth-page"><section className="auth-card"><div className="brand-mark">W</div><p className="eyebrow">SMART DAILY REPORT</p><h1>오늘의 업무를<br/>가볍게 기록하세요</h1><p className="muted">보고부터 프로젝트 관리, 승인까지 한곳에서.</p><form onSubmit={handleAuth}>{mode==="signup"&&<label>이름<input required value={auth.fullName} onChange={e=>setAuth({...auth,fullName:e.target.value})}/></label>}<label>이메일<input required type="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/></label><label>비밀번호<input required minLength={6} type="password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/></label>{notice&&<p className="error">{notice}</p>}<button className="primary full" disabled={busy}>{busy?"처리 중...":mode==="login"?"로그인":"직원 계정 만들기"}</button></form><button className="text-btn" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"처음이신가요? 계정 만들기":"이미 계정이 있나요? 로그인"}</button><small>처음 가입한 계정은 관리자 권한으로 설정됩니다.</small></section></main>;
 return <main className="app"><header><div><p className="eyebrow">MY WORK LOG</p><h1>나의 일일 업무보고</h1></div><button className="avatar" onClick={()=>supabase.auth.signOut()}>{(profile?.full_name||profile?.email||"나")[0]}</button></header><div className="content">{notice&&<div className="notice" onClick={()=>setNotice("")}>{notice}<b>×</b></div>}
 {tab==="home"&&<Dashboard profile={profile} today={today} reports={reports} projects={projects} openReport={openReport} setTab={setTab}/>}
 {tab==="report"&&<ReportEditor report={report} setReport={setReport} files={files} setFiles={setFiles} save={saveReport} busy={busy}/>}
 {tab==="projects"&&<Projects projects={projects} project={project} setProject={setProject} save={saveProject}/>}
 {tab==="admin"&&profile?.role==="admin"&&<Admin reports={reports} waiting={waiting} review={review}/>}</div>
 <nav><Nav active={tab==="home"} icon="⌂" label="홈" click={()=>setTab("home")}/><Nav active={tab==="report"} icon="✎" label="보고서" click={()=>openReport(new Date().toISOString().slice(0,10))}/><Nav active={tab==="projects"} icon="▦" label="프로젝트" click={()=>setTab("projects")}/>{profile?.role==="admin"&&<Nav active={tab==="admin"} icon="✓" label="승인관리" badge={waiting.length} click={()=>setTab("admin")}/>}</nav></main>
}
function Dashboard({profile,today,reports,projects,openReport,setTab}:any){return <><section className="welcome"><p>{new Intl.DateTimeFormat("ko-KR",{month:"long",day:"numeric",weekday:"long"}).format(new Date())}</p><h2>{profile?.full_name||"직원"}님,<br/>오늘도 좋은 하루예요.</h2></section><section className="today"><div><span className={`status ${today?.status||"none"}`}>{today?labels[today.status]:"미작성"}</span><h3>오늘의 업무보고</h3><p>{today?"작성한 내용을 확인하거나 이어서 작성하세요.":"오늘 한 일을 잊기 전에 기록해 보세요."}</p></div><button onClick={()=>openReport(new Date().toISOString().slice(0,10))}>→</button></section><Title title="진행 프로젝트" action={()=>setTab("projects")}/><div className="project-strip">{projects.filter((p:Project)=>p.status!=="completed").slice(0,3).map((p:Project)=><article className="mini-project" key={p.id}><div className="ring" style={{"--p":`${p.progress*3.6}deg`}as any}><span>{p.progress}%</span></div><div><b>{p.title}</b><p>{p.next_action||"다음 추진 사항을 입력하세요"}</p></div></article>)}{!projects.length&&<div className="empty">등록된 프로젝트가 없습니다.</div>}</div><Title title="최근 보고서"/><div className="list">{reports.slice(0,3).map((r:Report)=><button className="report-row" key={r.id} onClick={()=>openReport(r.report_date)}><span className="date"><b>{r.report_date.slice(8)}</b><small>{r.report_date.slice(5,7)}월</small></span><span><b>{r.completed_work.slice(0,34)||"업무 내용 미입력"}</b><small>{labels[r.status]}</small></span><i>›</i></button>)}{!reports.length&&<div className="empty">아직 작성한 보고서가 없습니다.</div>}</div></>}
function ReportEditor({report,setReport,files,setFiles,save,busy}:any){const locked=["submitted","approved"].includes(report.status),field=(key:keyof Report,label:string,hint:string)=><label className="field"><b>{label}</b><small>{hint}</small><textarea disabled={locked} value={report[key]as string||""} onChange={e=>setReport({...report,[key]:e.target.value})}/></label>;return <section className="editor"><PageTitle eyebrow="DAILY REPORT" title="일일 업무보고" extra={<span className={`status ${report.status}`}>{labels[report.status]}</span>}/><label className="date-field">보고일<input disabled={locked} type="date" value={report.report_date} onChange={e=>setReport({...report,report_date:e.target.value})}/></label>{report.manager_feedback&&<div className="feedback"><b>관리자 의견</b><p>{report.manager_feedback}</p></div>}{field("completed_work","오늘 한 일","완료한 업무와 성과를 구체적으로 적어주세요.")}{field("in_progress_work","진행 업무","현재 진행 중인 업무와 진척도를 적어주세요.")}{field("issues","문제점","업무 중 발생한 이슈나 어려움을 적어주세요.")}{field("actions_taken","조치 내용","문제 해결을 위해 취한 조치를 적어주세요.")}{field("tomorrow_plan","내일 할 일","내일의 우선순위와 예정 업무를 적어주세요.")}<label className="upload"><b>사진·파일 첨부</b><input disabled={locked} type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><div>＋ 파일 선택 <small>사진, PDF, 문서 · 최대 10MB</small></div></label>{files.map((f:File)=><p className="file" key={f.name}>{f.name}<small>{(f.size/1048576).toFixed(1)}MB</small></p>)}<div className="actions"><button className="secondary" onClick={()=>window.print()}>PDF 저장</button>{!locked&&<><button className="secondary" disabled={busy} onClick={()=>save(false)}>임시저장</button><button className="primary" disabled={busy} onClick={()=>save(true)}>제출하기</button></>}</div></section>}
function Projects({projects,project,setProject,save}:any){return <section><PageTitle eyebrow="KEY PROJECTS" title="주요 프로젝트"/><div className="project-list">{projects.map((p:Project)=><button key={p.id} className="project-card" onClick={()=>setProject({...p})}><div><span className={`status ${p.status}`}>{labels[p.status]}</span><b>{p.progress}%</b></div><h3>{p.title}</h3><p>{p.current_update||p.summary}</p><i><em style={{width:`${p.progress}%`}}/></i><small>다음 추진 사항 · {p.next_action||"미입력"}</small></button>)}</div><form className="project-form" onSubmit={save}><h3>{project.id?"프로젝트 수정":"새 프로젝트 등록"}</h3><label>프로젝트명<input required value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/></label><label>목표 및 개요<textarea value={project.summary} onChange={e=>setProject({...project,summary:e.target.value})}/></label><div className="grid"><label>상태<select value={project.status} onChange={e=>setProject({...project,status:e.target.value})}><option value="planned">예정</option><option value="active">진행 중</option><option value="blocked">지연</option><option value="completed">완료</option></select></label><label>진척도<input type="number" min="0" max="100" value={project.progress} onChange={e=>setProject({...project,progress:Number(e.target.value)})}/></label></div><label>진행 현황<textarea value={project.current_update} onChange={e=>setProject({...project,current_update:e.target.value})}/></label><label>추진 사항<textarea value={project.next_action} onChange={e=>setProject({...project,next_action:e.target.value})}/></label><label>위험·이슈<textarea value={project.risk} onChange={e=>setProject({...project,risk:e.target.value})}/></label><label>목표일<input type="date" value={project.target_date||""} onChange={e=>setProject({...project,target_date:e.target.value||null})}/></label><button className="primary full">프로젝트 저장</button></form></section>}
function Admin({reports,waiting,review}:any){return <section><PageTitle eyebrow="MANAGER" title="보고서 승인 관리" extra={<span className="count">{waiting.length}건 대기</span>}/><div className="stats"><div><b>{waiting.length}</b><small>승인 대기</small></div><div><b>{reports.filter((r:Report)=>r.status==="approved").length}</b><small>승인 완료</small></div><div><b>{reports.filter((r:Report)=>r.status==="revision_requested").length}</b><small>보완 요청</small></div></div><div className="approval-list">{reports.map((r:Report)=><article className="approval" key={r.id}><div className="approval-head"><span><b>{r.profiles?.full_name||r.profiles?.email||"직원"}</b><small>{r.profiles?.department||"소속 미입력"} · {r.report_date}</small></span><i className={`status ${r.status}`}>{labels[r.status]}</i></div><dl><dt>오늘 한 일</dt><dd>{r.completed_work||"-"}</dd><dt>문제점</dt><dd>{r.issues||"-"}</dd></dl>{r.status==="submitted"&&<div className="actions"><button className="secondary danger" onClick={()=>review(r.id,"revision_requested")}>보완 요청</button><button className="primary" onClick={()=>review(r.id,"approved")}>승인하기</button></div>}{r.manager_feedback&&<p className="feedback-line">관리자 의견 · {r.manager_feedback}</p>}</article>)}</div></section>}
function Title({title,action}:any){return <div className="section-title"><h3>{title}</h3>{action&&<button onClick={action}>전체보기</button>}</div>}function PageTitle({eyebrow,title,extra}:any){return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{extra}</div>}function Nav({active,icon,label,badge,click}:any){return <button className={active?"active":""} onClick={click}><i>{icon}</i><span>{label}</span>{badge>0&&<em>{badge}</em>}</button>}
